name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: docker-compose -f docker/docker-compose.yml run test
    - name: Run example
      run: docker-compose -f docker/docker-compose.yml run lazyk
